### ISSUE TITLE
Email doesn't show up when added through nux

### ISSUE THREAD

**Issue by thetomester13** [jasonmunro/hm3#1]
When I add an email account through nux, it doesn't automatically show up on the sidebar. I have to first hide it, and then show it, for it to show up on the sidebar.

**Comment by jasonmunro** [comment]
Interesting. The folder list is cached in the browser local storage, so when a new account is added we have a few steps we need to take to force it to reload. It's possible I missed one of the NUX flows with regards to the reload. I will see if I can reproduce it and fix it!

**Comment by jasonmunro** [comment]
Interestingly, this works fine for me in Chromium, but not Firefox. No console errors related to the issue either. I will dig into it and see whats going on.

**Comment by jasonmunro** [comment]
Fixed in https://github.com/jasonmunro/hm3/commit/e71b7ebfe6124201a9962dc0192d7153d4885b69 Thanks for the feedback!
