### ISSUE TITLE
Cypht doesn't support backslashes in passwords

### ISSUE THREAD

**Issue by bardo** [jasonmunro/hm3#103]
While investigating an IMAP login problem I turned on password debugging, and I saw that the password sent by Cypht was missing a backslash, which leads the login to fail.

There's probably some form of processing or sanitization of the password field that leads to this, I've given a quick look but I wasn't able to find it since I'm unfamiliar with the codebase.

**Comment by jasonmunro** [comment]
Hello!
Thanks for the feedback. I recently noticed that password fields were being filtered with INPUT_SANITIZE_STRING, which I changed to INPUT_UNSAFE_RAW.  I made this change about a week ago. If you update to the latest (or are already using the latest) and still have this problem, let me know and I will see if I can reproduce it.

Thanks again

**Comment by jasonmunro** [comment]
Also worth noting: Any time you update the code, you should rerun the config_gen script to pick up any changes that are cached by that process (which includes filter defs).

I did some more checking on this and was not able to reproduce the problem - I was able to pass a password to the IMAP server with backslashes included.

**Comment by bardo** [comment]
Hi! Thanks for your quick answer! I did re-run the config_gen script every time I changed the configuration or the code, so I should be good to go.

Regarding the version:
```
# git log -1 --shortstat  
commit 4d5620e8d383a4f19746c2d867735a3488a94074 
Author: Jason Munro <jason@hastymail.org> 
Date:   Fri Aug 5 17:38:11 2016 -0500 
 
    css tweak for the website logo 
 
 2 files changed, 2 insertions(+), 1 deletion(-)
```

Additionally, here's my dovecot debug log from when I reported the bug (a bit redacted, but the password is in clear, I already changed it anyway, and of course now it works):
```
Aug  7 00:40:47 $MYHOST dovecot: auth(default): client in: AUTH 1       PLAIN   service=imap    secured lip=$SERVERIP     rip=$CLIENTIP      lport=993       rport=50820     resp=$CHALLENGERESPONSE
Aug  7 00:40:47 $MYHOST dovecot: auth-worker(default): sql($MYUSER,$CLIENTIP): query: SELECT password FROM mailbox WHERE username = '$MYUSER'
Aug  7 00:40:47 $MYHOST dovecot: auth-worker(default): sql($MYUSER,$CLIENTIP): Password mismatch
Aug  7 00:40:47 $MYHOST dovecot: auth-worker(default): Invalid OTP data in passdb
Aug  7 00:40:47 $MYHOST dovecot: auth-worker(default): Invalid OTP data in passdb
Aug  7 00:40:47 $MYHOST dovecot: auth-worker(default): sql($MYUSER,$CLIENTIP): MD5(G(q0$=$aCgOP1(wWXI}5@Dz^) != '$SALTEDHASH'
Aug  7 00:40:47 $MYHOST dovecot: auth(default): new auth connection: pid=91330
Aug  7 00:40:49 $MYHOST dovecot: auth(default): client out: FAIL        1       user=$MYUSER
```

As you can see there is no backslash. The original password, however, was `G(q0$=$aCgOP1(w\WXI}5@Dz^`.

By comparison, here's a successful login with Thunderbird a few seconds later, obviously with the same password. The password here is not echoed by dovecot because the login did not fail, however I checked it manually, both in Thunderbird's password manager and in my general password manager.
(For completeness of information, my password manager generated this password randomly, and I copy-paste it everywhere, I never type it by hand.)
```
Aug  7 00:41:11 $MYHOST dovecot: auth(default): client in: AUTH 1       PLAIN   service=imap    secured lip=$SERVERIP     rip=$CLIENTIP      lport=993       rport=29448
Aug  7 00:41:11 $MYHOST dovecot: auth(default): client out: CONT        1
Aug  7 00:41:11 $MYHOST dovecot: auth(default): client in: CONT 1       $CHALLENGERESPONSE
Aug  7 00:41:11 $MYHOST dovecot: auth-worker(default): sql($MYUSER,$CLIENTIP): query: SELECT password FROM mailbox WHERE username = '$MYUSER'
Aug  7 00:41:11 $MYHOST dovecot: auth(default): client out: OK  1       user=$MYUSER
Aug  7 00:41:11 $MYHOST dovecot: auth(default): master in: REQUEST      2       91330   1
Aug  7 00:41:11 $MYHOST dovecot: auth-worker(default): sql($MYUSER,$CLIENTIP): SELECT '$MAILDIR' as home, 'maildir:$MAILDIR' as mail, 150 AS uid, 6 AS gid, concat('dirsize:storage=',quota) AS quota FROM mailbox WHERE username ='$MYUSER' AND active ='1'
Aug  7 00:41:11 $MYHOST dovecot: auth(default): master out: USER        2       $MYUSER    home=$MAILDIR    mail=maildir:$MAILDIR    uid=150 gid=6   quota=dirsize:storage=0
Aug  7 00:41:11 $MYHOST dovecot: imap-login: Login: user=<$MYUSER>, method=PLAIN, rip=$SERVERIP, lip=$CLIENTIP, TLS
Aug  7 00:41:12 $MYHOST dovecot: auth(default): new auth connection: pid=91333
```

I don't think it's really useful information, however the software stacks are:
- client: Devuan ascii (aka testing), PHP 7.0.9, nginx 1.10.1
- server: FreeBSD 9.3, dovecot 1.2.17

Let me know if there is any other information I can provide you!

**Comment by jasonmunro** [comment]
Thanks for the very thorough response! I believe I have found the issue. Backslashes need to be escaped before being sent to the IMAP server. I committed a fix in https://github.com/jasonmunro/hm3/commit/d3e1aaa27a96569ffe764ad0da9bb53b5a92af4b

Could you pull this and see if it resolves your issue? You don't need to rebuild the config for this changes to take effect.

**Comment by bardo** [comment]
It looks like I can't login with my non-backslashed password now. I pulled the files, fixed the permissions, merged the config with the sample just to be sure and ran the config_gen script, but every time I try to log in I'm sent back to the form.

I don't want to derail this discussion and I feel I haven't tested enough to file another bug, so I'll try again as soon as I have som more time, maybe reverting to the old commit and, if it works, bisecting to the head.

**Comment by jasonmunro** [comment]
This is my bad. Array arguments to str_replace are processed in order, so this fix broke passwords with a double quote :) Fixed again in https://github.com/jasonmunro/hm3/commit/7c4efea508f67ebae263bd7eab7312f382cadbce

**Comment by bardo** [comment]
Confirmed working, with or without backslashes. Thanks a lot!
