### ISSUE TITLE
Cypht does not play nice with other applications

### ISSUE THREAD

**Issue by L3CC** [jasonmunro/hm3#104]
I was trying to call Cypht from another web app and found that each time Cypht login page was called the other app session's data was lost. Checking the code I found that all session data is cleared by Cypth at login page. I can understand why but I also needed to keep previous session data. I've also found that, when clearing session data, Cypht expects 'session.name' to always be 'PHPSESSIONID', which is not correct. Sometimes is something else. However the solution for both cases is not difficult.

Add the following to lib/ini_set.php:
ini_set('session.name', 'CYPHTID');
Then edit lib/session.php and modules/core/setup.php and replace 'PHPSESSIONID' by 'CYPHTID'.

This way not only existing session data, from other apps, is preserved but Cypht will properly set and clear it's own session data when PHP session name is not standard.

**Comment by jasonmunro** [comment]
Hello! Thanks for the great feedback. I just committed your suggested changes in https://github.com/jasonmunro/hm3/commit/ed8385fb3d01544030482fd06bcebb0c8ac0dbd1
