### ISSUE TITLE
Compose page features

### ISSUE THREAD

**Issue by jasonmunro** [jasonmunro/hm3#16]
The compose page is very limited right now, it needs:

- Cc/Bcc support
- attachments (once a system is built for that)
- proper reply formatting
- saving of sent message outside auto-save via Gmail
- probably more

**Comment by dumblob** [comment]
With `proper reply formatting` you meant among other things also `Reply-To:`?

**Comment by jasonmunro** [comment]
I was thinking more about the fact we are not correctly setting In-reply-to on the outbound message (this should be set to the original message-id header), and that we should be flipping the IMAP Answered flag on the original. If we are not properly setting Reply-to on the outbound message, then yes, lets include that :)

**Comment by jasonmunro** [comment]
Cc/Bcc support is done

**Comment by jasonmunro** [comment]
in-reply-to and reply-to headers are now supported. reply-to is not settable currently, it just defaults to the From header values

**Comment by jasonmunro** [comment]
This is complete except for saving sent messages in an imap folder. I'm going to close this and open more specific issues for anything that remains.
