### ISSUE TITLE
Support more than 4 IMAP Servers

### ISSUE THREAD

**Issue by R-J** [jasonmunro/hm3#21]
Seems like only 4 IMAP servers are supported. I must admit: I really have more than that...

**Comment by jasonmunro** [comment]
There is no limit on the number of IMAP servers you can add, I have had over 10 in a test setup before. The UI will "wrap" to another row of servers, so be sure and scroll down after adding the 5th and you should see it.

**Comment by R-J** [comment]
Not sure what happened, but you are right and there is no such limit
