### ISSUE TITLE
Don't delete SMTP Server fields when port is wrong

### ISSUE THREAD

**Issue by R-J** [jasonmunro/hm3#22]
I've tried to add a SMTP server and I have chosen the wrong port. The connection failed and my input (not much, only the account name and the server address) was lost because the side reloaded. Having the fields prepopulated with the values of the last try would be more comfortable.

**Comment by jasonmunro** [comment]
Added in https://github.com/jasonmunro/hm3/commit/c5e21871fef448ffe5030ee523dd020f5cd37ded Thanks for the feedback!
