### ISSUE TITLE
Prepopulate port fields for "Add server"

### ISSUE THREAD

**Issue by R-J** [jasonmunro/hm3#23]
When I was adding IMAP servers I always had to type "993" into the port field. It would be nice if those port fields are prepopulated with meaningful values. I'd suggest
IMAP: 993
POP3: 995
SMTP: 465

**Comment by jasonmunro** [comment]
Great idea! Added in https://github.com/jasonmunro/hm3/commit/483dcb39f7a36ff2f21f6b06ccd40e9f1b7a9329
