### ISSUE TITLE
Deleting messages doesn't work

### ISSUE THREAD

**Issue by thetomester13** [jasonmunro/hm3#3]
When I select a message and click delete, the message is still in the folder where it was located before. Also, it takes me back to the 'Home' screen; it would be nice if it could redirect me to the same page where I was before. Even better, asynchronous call?

**Comment by jasonmunro** [comment]
This is a bug. Deleting messages should be async and not redirect you anywhere :). I can't reproduce this in FF or Chromium. Does the same thing happen when you try flag/unflag/read/unread? Are there any js errors in the console when you get redirected? Anything interesting in the server side debug output?

**Comment by thetomester13** [comment]
Don't know what happened but I pulled again and now it works!
