### ISSUE TITLE
Demo or screenshots?

### ISSUE THREAD

**Issue by itsazzad** [jasonmunro/hm3#45]
Do you have any Demo or screenshots?

**Comment by jasonmunro** [comment]
There is one out of date tiny screenshot at cypht.org, aside from that I haven't taken the time to upload any more. There is no public demo site yet, but I do host a publicly accessible instance. If you would like a demo account on that site let me know and I will set one up for you.

**Comment by itsazzad** [comment]
Yes that would be great if I would be able to have the demo experience before playing in deep.
itsazzad@gmail.com is my email.

**Comment by jasonmunro** [comment]
@beta-phenylethylamine happy to give you a demo account. Please E-mail me at jason at cypht dot org for details. I'm also in the #hastymail channel at freenode most of the time. Thanks for your interest in the project.
