### ISSUE TITLE
Problem in character encoding in Yahoo imap folders

### ISSUE THREAD

**Issue by 8wmas** [jasonmunro/hm3#48]
I tested the software yesterday and I saw strange characters (I think that they were utf8 encodings) in the folder names of a yahoo imap account.
The folder names were in Greek

**Comment by jasonmunro** [comment]
Thanks for the feedback. I will test this out and see what I can do.

**Comment by jasonmunro** [comment]
Confirmed this bug and fixed it with the following commit:

https://github.com/jasonmunro/hm3/commit/bb4f556344f73c913198c5d86931cfdc8773e080

The IMAP library has the ability to handle non-ascii folder name conversion per the RFC, we just did not have it enabled! Thanks again for the feedback.

**Comment by jasonmunro** [comment]
well, the folder with greek letters displays properly in the folder list, but trying to access it causes multiple errors:

- javascript errors thrown about a invalid selector
- bad formatting of the folder name in the message list heading
- probably more!

Re-opening this until I clean the rest of these issues up.

**Comment by jasonmunro** [comment]
OK, I think this is resolved now. We had some hacky work-arounds for odd-ball folder names, but they obviously did not correctly handle a pure non-ascii value. I just pushed the following change-set that utilizes bin2hex and hex2bin to "encode" a folder name so it can be passed around safely in the UI:

https://github.com/jasonmunro/hm3/commit/060a4bd2cb6f0453f22544397f9403371f6ea9e5

This is a much more comprehensive fix than the hacky stuff I had in place before, so thanks again for the report! Any change you could re-test with the current master branch and let me know if it's working correctly?
