### ISSUE TITLE
HTML messages should have a download link at least

### ISSUE THREAD

**Issue by mat-m** [jasonmunro/hm3#51]
Hello

Currently if an IMAP message is composed in HTML only, nothing is shown in inline message view

Markers are:
```
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable
```

We should have a line like below at least.
```
text / html				7bit			utf-8		Download
```

A nice-to-have is a "View" link to open the content part in a popup window. It is useful when you trust the sender and don't want to download the html to read it.

**Comment by jasonmunro** [comment]
> Currently if an IMAP message is composed in HTML only, nothing is shown in inline message view

This might be a bug specific to the inline message view, I have not run into this problem before. There should be a view link at the bottom of the message, and of course unless the message is empty, the html should be displayed.

**Comment by mat-m** [comment]
I can send you the mail as a test. Whether it is inline or standalone message view, the result is the same.

I am on the debug version and no `View` link appear

**Comment by jasonmunro** [comment]
If you can send me the message that would help a lot. jason@hastymail.org. Thanks

**Comment by jasonmunro** [comment]
I can't repeat this problem with the message in question. I E-mailed you a screenshot of this particular message and it renders properly for me. Please re-open this issue if you are still having problems. Thanks!
