### ISSUE TITLE
Raw view cannot be undone

### ISSUE THREAD

**Issue by mat-m** [jasonmunro/hm3#52]
If I choose to display the raw view of the message, I got it again if I go back to this message in the same session.

I suggest that clicking again on "Raw" will hide it.

**Comment by jasonmunro** [comment]
The last view of the message is cached, so whatever part, or all parts (raw) is what you get when you go back. I agree we  should toggle the raw view with the link. You can scroll all the way down to the message parts then select one of those, but thats a pain :)

**Comment by jasonmunro** [comment]
Fixed in https://github.com/jasonmunro/hm3/commit/fc52f894658913e2968ede7ae90c7f038e234588 Thanks for the feedback!
