### ISSUE TITLE
Translation hickup in title bar

### ISSUE THREAD

**Issue by mat-m** [jasonmunro/hm3#53]
When checking for translation, I saw that  accentuated chars are displayed as raw html in the top-right bar where there is the filter information, namely the scan delay (`è` is rendered as `&egrave;`). This does not occur on other areas like menu or main parts. The title of the right area (the one after the check-box) displays the right accentuated character.

**Comment by jasonmunro** [comment]
Good catch! Fixed in: https://github.com/jasonmunro/hm3/commit/66b359e3a0718f46226404d50bdea9bbf8186c61
