### ISSUE TITLE
Problem with config generation

### ISSUE THREAD

**Issue by mat-m** [jasonmunro/hm3#54]
After latest git pull (commit a9be0969fc29fdf), I have the following output :

`# php  scripts/config_gen.php`
> scanning module core ...
> scanning module contacts ...
> scanning module feeds ...
> scanning module imap ...
> scanning module smtp ...
> scanning module site ...
> scanning module account ...
> scanning module idle_timer ...
> scanning module calendar ...
> scanning module themes ...
> scanning module nux ...
> scanning module developer ...
> scanning module github ...
> scanning module wordpress ...
> scanning module history ...
> scanning module saved_searches ...
> scanning module nasa ...
> sh: 431: 1: not found
> sh: echo: I/O error
> site.css file created
> sh: 2906: 1: not found
> sh: echo: I/O error
> site.js file created
> hm3.rc file written
> creating production site

I don't know if it could be related to my setup or not (site.css is 0 byte)

**Comment by jasonmunro** [comment]
I'm not seeing this here. Do you have a css_compress setting set in your hm3.ini? If so that might be the source of the problem. We shell out to compress css with the command specified in that setting. If you do have it set to something, maybe try disabling it by setting it to false. Another possibility is file permission issues, but since the other files are created that seems less likely.

**Comment by mat-m** [comment]
It was set to ` true ` and working. Setting them to ` false ` makes things work again.
Strange. Since I upgraded from Debian jessie to Debian wheezy, something might have changed in-between.

**Comment by jasonmunro** [comment]
Weird that it worked when set to true. We should definitely do some better error checking in the config script. If the output of the compression command does not return anything, we should issue a warning and use the uncompressed content. Should have a patch for that today or tomorrow. Thanks for the follow up!

**Comment by jasonmunro** [comment]
The config generation script has been updated to check the results of the compression command, and use the uncompressed content if it fails. https://github.com/jasonmunro/hm3/commit/07ff2131b380ab945750a259ed7a9f7577e8909d
