### ISSUE TITLE
 Fatal error: Can't use method return value in write context

### ISSUE THREAD

**Issue by gevatter** [jasonmunro/hm3#6]
I just wantet to try out cypth but when accessing the page i get

    Fatal error: Can't use method return value in write context in /var/www/cypht/hm3-master/modules/core/modules.php on line 848

It doesent matter, if I use the main dir or the site dir as document root.

    # php -v
    PHP 5.4.39-0+deb7u2 (cli) (built: Mar 25 2015 08:33:29)
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by jasonmunro** [comment]
Thanks for the report! I was not aware of that particular behavior WRT empty() in PHP versions less than 5.5. I fixed this instance and a few others I found in this commit: https://github.com/jasonmunro/hm3/commit/610860afcee360fc69f95ab08791be40c768f9cf

**Comment by gevatter** [comment]
Thanks, its working for me. I have an other question, but I will open an other issue for that.
