### ISSUE TITLE
Moving NASAAPIs Box in Settings - Server

### ISSUE THREAD

**Issue by Fvbor** [jasonmunro/hm3#61]
Hi Jason,

here, a little display failure.
Settings - Server
https://cypht.com/?page=servers

Click on Github Connect -> NASA APIs is moving to the right.
See the three pictures:
![20160418-081249_picpick](https://cloud.githubusercontent.com/assets/18524580/14595457/b2c50786-053f-11e6-9d1a-cc7be57d22b9.png)
![20160418-081252_picpick](https://cloud.githubusercontent.com/assets/18524580/14595456/b2c4febc-053f-11e6-9109-5a42b2c1d24b.png)
![20160418-081258_picpick](https://cloud.githubusercontent.com/assets/18524580/14595455/b2c41614-053f-11e6-8b11-2b535e1e81b4.png)

Browser:
Chrome
Firefox
Opera
IE

Thanks!
Have a nice day
Nice regards
Hagen

**Comment by jasonmunro** [comment]
Thanks for the feedback. Fixed in the follwoing commit: https://github.com/jasonmunro/hm3/commit/d21eed2b17c8c908890e14be02dd8dfd50db8dc2
