### ISSUE TITLE
Flagging and reloading creates new relative emails

### ISSUE THREAD

**Issue by Fvbor** [jasonmunro/hm3#62]
Open an Email
```
While True:
   click on flag/unflag
   reload the page
```
And you will see this:
![image](https://cloud.githubusercontent.com/assets/18524580/14619302/2caa442c-05b7-11e6-82ef-c273674a949e.png)

After logoff (with save) and login everything is ok.

**Comment by jasonmunro** [comment]
Fixed in https://github.com/jasonmunro/hm3/commit/fb7e285e76f766e60350e561a5e7cc76e419c927 Thanks for the feedback!
