### ISSUE TITLE
Count of unread Emails in the title is multiplied with two

### ISSUE THREAD

**Issue by Fvbor** [jasonmunro/hm3#63]
One new mail -> Title is "2 Unread in Everything"
Two new Mail -> Title is "4 Unread in Everything"
See image:
![image](https://cloud.githubusercontent.com/assets/18524580/14619447/ea3d3c88-05b7-11e6-863d-ae3e8de30fc4.png)

**Comment by jasonmunro** [comment]
Fixed in https://github.com/jasonmunro/hm3/commit/f2c2b7ffba300644776dc728c5235f17aabd8518 Thanks for the feedback!
