### ISSUE TITLE
Text which are not using the Translation methode

### ISSUE THREAD

**Issue by Fvbor** [jasonmunro/hm3#64]
These text are not using the Translation methode

**On the Contacts Page**
Contact Deleted
Contact Added
Contact Updated
Update Local Contact

**On the Event Page**
Add an Event
Time
Repeat
Title
Detail
Event Created
Repeats every day
Delete (Translation exist, but it is not used - Event Information)
Event Deleted

**On the Mail Page**
Seen
Flagged (Translation exists, but it is not used - Tags of the Email)

**Comment by jasonmunro** [comment]
Added missing strings here: https://github.com/jasonmunro/hm3/commit/7eaf23991ccf642cc367d764caec497e22254213 and fixed tags translation as a part of this commit: https://github.com/jasonmunro/hm3/commit/71a7a186ce13501d168c8e215e88047d8ffd1b6f
